### ISSUE TITLE
sort notes

### ISSUE THREAD

**Issue by wildskyf** [wildskyf/tab-notes#21]
as mentioned by @jenhsun and @grahamperrin in [#8](https://github.com/wildskyf/tab-notes/issues/8#issuecomment-577413333)

We need to better sort experience

**Comment by wildskyf** [comment]
implemented in v2.3.0

**Comment by jenhsun** [comment]
@wildskyf It works, thanks.

**Comment by jenhsun** [comment]
@wildskyf Hopefully you can implement v.2.3.0 on Chrome someday, thanks.

**Comment by wildskyf** [comment]
@jenhsun I just published it on chrome extension store at [here](https://chrome.google.com/webstore/detail/tab-notes/obnnegakmgonaiplaobihpmcjhlceeic). Thanks for your reminder.

**Comment by jenhsun** [comment]
@wildskyf It works, thanks. Recently I have to switch to Brave browser due to Firefox's lousy performance. And Brave uses chrome extension because it's chromium based without Google's involvement.  

Thanks again anyway.
