### ISSUE TITLE
broken by FF 80.0a1

### ISSUE THREAD

**Issue by aminomancer** [wildskyf/tab-notes#24]
You might notice the notes no longer save in firefox branch 80. The update/storage just fails:
```
Uncaught (in promise) Error: QuotaExceededError: storage.sync API call exceeded its quota limitations. undefined
    apply self-hosted:2380
    applySafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:613
    wrapPromise resource://gre/modules/ExtensionCommon.jsm:888
    (Async: promise callback)
    wrapPromise resource://gre/modules/ExtensionCommon.jsm:849
    wrapPromise resource://gre/modules/ExtensionCommon.jsm:848
    callAsyncFunction resource://gre/modules/ExtensionCommon.jsm:1090
    callAsyncFunction resource://gre/modules/ExtensionChild.jsm:701
    callAndLog resource://gre/modules/ExtensionChild.jsm:677
    callAsyncFunction resource://gre/modules/ExtensionChild.jsm:700
    stub resource://gre/modules/Schemas.jsm:2690
    write_timeout moz-extension://c2ad9663-e5fd-4621-b01d-d95f7faf0e00/newtab.js:118
    (Async: setTimeout handler)
    _noteEventHandler moz-extension://c2ad9663-e5fd-4621-b01d-d95f7faf0e00/newtab.js:109
```

Also, with this (and several other new tab page extensions) installed, opening a new tab no longer focuses the urlbar, it focuses the tab notes input box. Making it multiple clicks to type in a url or search query. This is firefox's fault obviously but since the default new tab page works fine it seems like they've moved some code from the UI to the new tab page. This could be fixed with javascript I guess, I'm looking through the code for the new tab page to try to figure out why it works but a custom NTP doesn't. There are some bug reports about this: https://bugzilla.mozilla.org/show_bug.cgi?id=1628541

**Comment by aminomancer** [comment]
Also I see this on MDN: The main use case of this API is to store preferences about your extension and allow the user to sync them to different profiles. You can store up to 100KB of data using this API.

**Comment by aminomancer** [comment]
https://blog.mozilla.org/addons/2020/07/09/changes-to-storage-sync-in-firefox-79/

**Comment by aminomancer** [comment]
Maybe use storage.local instead and set "permissions":["storage", "unlimitedStorage"]

**Comment by aminomancer** [comment]
i can confirm that replacing all instances of storage.sync get/set with storage.local fixes the updating issue. however i don't know if it's possible to fix the focus issue. my javascript attempts aren't working correctly. according to https://bugzilla.mozilla.org/show_bug.cgi?id=1651372 this might be caused by the browser fissioning the browser in a separate process so i guess that might be why the default NTP works fine despite no locally loaded scripts

**Comment by wildskyf** [comment]
@aminomancer 
Yeah, the only solution is to change storage from `sync` to `local`...

I just upload v3.1.0, try it! 
https://addons.mozilla.org/addon/tab-notes/
