### ISSUE TITLE
capture keyboard save

### ISSUE THREAD

**Issue by keramitsis** [wildskyf/tab-notes#6]
Hi there,

first, i use your add-on daily and i love it! It's simple and does it's job.

Out of behaviour i often press "cmd + s" and the browser "save page" dialogue pops up.
Capturing this and triggering a save or even doing nothing (because it should be saved by this time) seems like a good idea!?

I would try to implement it and give you a pull request if you think that's sound like a good idea? 

Cheers!

**Comment by wildskyf** [comment]
hahaha, Good suggestion!
I will implement it in the next version. :D

**Comment by keramitsis** [comment]
just noticed that you implemented it! Very nice!

**Comment by wildskyf** [comment]
;)

Feel free to open another issue or feature request!
