### ISSUE TITLE
Multiple Notes

### ISSUE THREAD

**Issue by olegbl** [wildskyf/tab-notes#8]
Being able to create/save multiple notes with some simple interface to switch between them would be great. (e.g. Chrome extension https://chrome.google.com/webstore/detail/new-tab-draft/nmfjkeiebceinkbggliapgfdjphocpdh)

**Comment by grahamperrin** [comment]
I aimed to use [Page Memo](https://addons.mozilla.org/firefox/addon/page-memo/) to place floating notes at 

moz-extension://2f2af2b3-644b-4c8a-be50-561bc18dd10e/newtab.html

– but of course it can not be done within the constraints of WebExtensions APIs :-(

----

Personally, I love Tab Notes 1.4.0. Its simplicity is a strength.

**Comment by wildskyf** [comment]
Hi @olegbl and @grahamperrin 

The latest version v2.0.1 has supported multi notes feature!
Please try it and give me some feedback (if you are willing to). :)

**Comment by grahamperrin** [comment]
Thanks!

Nit: after emptying, it's possible to have multiple empty notes –

![image](https://user-images.githubusercontent.com/192271/62413788-05d12980-b60b-11e9-8698-36fcf2b2cf47.png)

– and the circled cross ⨯ is ambiguous, I refrained from clicking because I assumed that it would collapse the sidebar.

**Comment by wildskyf** [comment]
@grahamperrin Thanks for your feedback!
and I need to find better interactive behavior...

What about this: change the `⨯` to a pencil icon, and by clicking it list will show you `⨯` for each note in order to delete the certain note.

**Comment by grahamperrin** [comment]
I think, a pencil (edit) icon at the head of the column could mislead users into believing that each note has an editable title. 

The plus icon is good, I think. At the head of the column. Don't have it morph into anything else in the same position. 

How about a miniature trash icon for each note? Never hidden (always visible, when the column is visible) …

**Comment by ofbillow** [comment]
希望把待办和已完成放在一个面页中，分成上下两个清单，中间简单间隔，如果待办事项被标记为已完成，就自动调到下面的已完成的里面去。

这是google keep的待办清单里的效果，很方便，希望能有这个效果！> . <

**Comment by jenhsun** [comment]
@wildskyf Nice tab notes extension. Thanks.   

A little suggestion: It's looked like the oldest note always stacking on the top of other notes. When I click +, it always create a new note at the bottom. Could you change it to the top?  I hope when I open browser, it could show the top note first.

**Comment by grahamperrin** [comment]
> … change it to the top? …

I prefer as is: chronological order (not reversed). 

Maybe reversal can be a user preference.

**Comment by jenhsun** [comment]
@grahamperrin Agree. I think chronological order by note's modified date/time is what I mean, thank for clarify it. Newest on the most top of the order. And when I open tab notes, it will show  the latest modified note.

**Comment by wildskyf** [comment]
@ofbillow 嗨，謝謝你提供這個 idea，不過你提到的功能並不屬於 issue 的範圍，所以我另外開了 #20 以追蹤這個新功能的開發進度

@jenhsun @grahamperrin  Thank you two for discuss the sort issue. I have opened a new issue #21 for it.

---

And I just published a new version v2.2.0, which simply the delete function. :)
Feel free to leave comment if you face any problems.

**Comment by wildskyf** [comment]
Resolve by #21 closed
